/* parser generated by jison 0.4.15 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,8],$V1=[6,8,13],$V2=[1,22],$V3=[1,14],$V4=[1,26],$V5=[1,23],$V6=[1,24],$V7=[1,25],$V8=[1,21],$V9=[6,8,13,17,34,35,37,40,44],$Va=[8,13,17,34,35,37,40,44],$Vb=[1,45],$Vc=[42,43],$Vd=[14,15,18,25],$Ve=[1,59],$Vf=[1,60],$Vg=[29,30],$Vh=[14,15,18,25,29,30,31];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"root":3,"document":4,"complete_elements":5,"EOF":6,"complete_element":7,"SPACE":8,"open_tag":9,"close_tag":10,"element_content":11,"self_closing_tag":12,"OPEN_TAG":13,"WORD":14,"CLOSE_TAG":15,"attributes":16,"TAG_CLOSER":17,"SELF_TAG_CLOSER":18,"contents":19,"variable":20,"djtag":21,"comment":22,"html_entity":23,"attribute":24,"TAG_SPACE":25,"EQUAL":26,"quote":27,"attribute_content":28,"BEG_QUOTE":29,"END_QUOTE":30,"ATTRIB_CONTENT":31,"non_variable_attr_content":32,"words":33,"HTML_ENTITY":34,"OPEN_VAR":35,"CLOSE_VAR":36,"OPEN_DJTAG":37,"CLOSE_DJTAG":38,"COMMA":39,"COMMENT_BEGIN":40,"comment_content":41,"COMMENT_END":42,"COMMENT_CONTENT":43,"CONTENT":44,"$accept":0,"$end":1},
terminals_: {2:"error",6:"EOF",8:"SPACE",13:"OPEN_TAG",14:"WORD",15:"CLOSE_TAG",17:"TAG_CLOSER",18:"SELF_TAG_CLOSER",25:"TAG_SPACE",26:"EQUAL",29:"BEG_QUOTE",30:"END_QUOTE",31:"ATTRIB_CONTENT",34:"HTML_ENTITY",35:"OPEN_VAR",36:"CLOSE_VAR",37:"OPEN_DJTAG",38:"CLOSE_DJTAG",39:"COMMA",40:"COMMENT_BEGIN",42:"COMMENT_END",43:"COMMENT_CONTENT",44:"CONTENT"},
productions_: [0,[3,1],[4,0],[4,2],[5,1],[5,1],[5,2],[5,2],[7,2],[7,3],[7,1],[9,3],[9,4],[10,3],[12,3],[12,4],[11,1],[11,1],[11,1],[11,1],[11,1],[11,1],[11,2],[11,2],[11,2],[11,2],[11,2],[11,2],[16,1],[16,1],[16,2],[16,2],[24,5],[27,1],[27,1],[28,0],[28,1],[32,1],[32,1],[32,1],[32,2],[32,2],[32,2],[33,1],[33,2],[33,2],[23,1],[20,3],[21,6],[21,4],[21,10],[21,13],[22,3],[41,1],[41,2],[19,1],[19,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

      this.$ = $$[$0]
    
break;
case 11:
this.$ = yy.visitor.visitOpenElement(yy.ast, $$[$0-1]);;
break;
case 12:
this.$ = yy.visitor.visitOpenElement(yy.ast, $$[$0-2]);;
break;
case 13:
this.$ = yy.visitor.visitCloseElement(yy.ast, $$[$0-1]);;
break;
case 14:

      yy.visitor.visitSelfClosingElement(yy.ast, $$[$0-1]);
    
break;
case 15:

      yy.visitor.visitSelfClosingElement(yy.ast, $$[$0-2]);
    
break;
case 32:

      yy.visitor.visitAttribute(yy.ast, $$[$0-4], $$[$0-1]);
    
break;
case 46:
this.$ = yy.visitor.visitHTMLEntity(yy.ast, $$[$0]);;
break;
case 47:
this.$ = yy.visitor.visitVariable(yy.ast, $$[$0-1]);;
break;
case 48:
this.$ = yy.visitor.visitComputeDjtag(yy.ast, $$[$0-4], $$[$0-2]);;
break;
case 49:
this.$ = yy.visitor.visitSignalDjtag(yy.ast, $$[$0-2]);;
break;
case 50:

      yy.visitor.visitForDjtag(yy.ast, $$[$0-8], null, $$[$0-6], $$[$0-4], $$[$0-2]);
    
break;
case 51:

      yy.visitor.visitForDjtag(yy.ast, $$[$0-11], $$[$0-9], $$[$0-6], $$[$0-4], $$[$0-2]);
    
break;
case 55:
this.$ = yy.visitor.visitText(yy.ast, $$[$0]);;
break;
case 56:
this.$ = yy.visitor.visitText(yy.ast, " ");;
break;
}
},
table: [{1:[2,2],3:1,4:2,5:3,7:4,8:[1,5],9:6,12:7,13:$V0},{1:[3]},{1:[2,1]},{6:[1,9],7:10,8:[1,11],9:6,12:7,13:$V0},o($V1,[2,4]),o($V1,[2,5]),{7:15,8:$V2,9:6,10:12,11:13,12:7,13:$V0,17:$V3,19:16,20:17,21:18,22:19,23:20,34:$V4,35:$V5,37:$V6,40:$V7,44:$V8},o($V9,[2,10]),{14:[1,27]},{1:[2,3]},o($V1,[2,6]),o($V1,[2,7]),o($V9,[2,8]),{7:29,8:$V2,9:6,10:28,12:7,13:$V0,17:$V3,19:30,20:31,21:32,22:33,23:34,34:$V4,35:$V5,37:$V6,40:$V7,44:$V8},{14:[1,35]},o($Va,[2,16]),o($Va,[2,17]),o($Va,[2,18]),o($Va,[2,19]),o($Va,[2,20]),o($Va,[2,21]),o($Va,[2,55]),o($Va,[2,56]),{14:[1,36]},{14:[1,37]},{41:38,43:[1,39]},o($Va,[2,46]),{14:$Vb,15:[1,40],16:41,18:[1,42],24:43,25:[1,44]},o($V9,[2,9]),o($Va,[2,22]),o($Va,[2,23]),o($Va,[2,24]),o($Va,[2,25]),o($Va,[2,26]),o($Va,[2,27]),{15:[1,46]},{36:[1,47]},{8:[1,48]},{42:[1,49],43:[1,50]},o($Vc,[2,53]),o($Va,[2,11]),{14:$Vb,15:[1,51],18:[1,52],24:53,25:[1,54]},o($V9,[2,14]),o($Vd,[2,28]),o($Vd,[2,29]),{26:[1,55]},o($V9,[2,13]),o($Va,[2,47]),{14:[1,56],38:[1,57]},o($Va,[2,52]),o($Vc,[2,54]),o($Va,[2,12]),o($V9,[2,15]),o($Vd,[2,30]),o($Vd,[2,31]),{27:58,29:$Ve,30:$Vf},{8:[1,61],39:[1,62]},o($Va,[2,49]),o($Vg,[2,35],{28:63,31:[1,64]}),o($Vh,[2,33]),o($Vh,[2,34]),{14:[1,66],38:[1,65]},{8:[1,67]},{27:68,29:$Ve,30:$Vf},o($Vg,[2,36]),o($Va,[2,48]),{8:[1,69]},{14:[1,70]},o($Vd,[2,32]),{14:[1,71]},{8:[1,72]},{8:[1,73]},{14:[1,74]},{38:[1,75]},{8:[1,76]},o($Va,[2,50]),{14:[1,77]},{8:[1,78]},{38:[1,79]},o($Va,[2,51])],
defaultActions: {2:[2,1],9:[2,3]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        throw new Error(str);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        function lex() {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        }
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return "TAG_SPACE"
break;
case 1:return "SPACE"
break;
case 2:
                                  this.begin('tag');
                                  return "OPEN_TAG"
                                
break;
case 3:
                                  this.begin('tag');
                                  return "TAG_CLOSER"
                                
break;
case 4:
                                  this.begin('INITIAL');
                                  return "CLOSE_TAG"
                                
break;
case 5:
                                  this.begin('INITIAL');
                                  return "SELF_TAG_CLOSER" 
                                
break;
case 6:
                                  this.begin('attribval')
                                  return "BEG_QUOTE"
                                
break;
case 7:
                                  this.begin('tag')
                                  return "END_QUOTE"
                                
break;
case 8:return "ATTRIB_CONTENT"
break;
case 9:return "EQUAL"
break;
case 10:
                                  this.begin('comment')
                                  return "COMMENT_BEGIN"
                                
break;
case 11:
                                  this.begin('INITIAL');
                                  return "COMMENT_END"
                                
break;
case 12:
                                  return "COMMENT_CONTENT"
                                
break;
case 13:
                                  return "COMMENT_CONTENT"
                                
break;
case 14:
                                  this.begin('var');
                                  return "OPEN_VAR"
                                
break;
case 15:
                                  this.begin('INITIAL');
                                  return "CLOSE_VAR"
                                
break;
case 16:
                                  this.begin('djtag');
                                  return "OPEN_DJTAG"
                                
break;
case 17:
                                  this.begin('INITIAL');
                                  return "CLOSE_DJTAG"
                                
break;
case 18:return "COMMA"
break;
case 19:return "HTML_ENTITY"
break;
case 20:return "HTML_ENTITY"
break;
case 21:return "WORD"
break;
case 22:return "WORD"
break;
case 23:
                                  this.begin("escape");
                                
break;
case 24:
                                  this.begin("INITIAL");
                                
break;
case 25:return "EOF"
break;
case 26:return "CONTENT"
break;
}
},
rules: [/^(?:\s+)/,/^(?:\s+)/,/^(?:<(?=\w+))/,/^(?:<\/(?=\w+))/,/^(?:>)/,/^(?:\/>)/,/^(?:["\"'"])/,/^(?:["\"'"])/,/^(?:[^"\"'"]+)/,/^(?:=)/,/^(?:<!--)/,/^(?:-->)/,/^(?:\s)/,/^(?:.)/,/^(?:\{\{\s*)/,/^(?:\s*\}\})/,/^(?:\{%\s*)/,/^(?:%\})/,/^(?:\s*,)/,/^(?:&#x\d{4};)/,/^(?:&\w+;)/,/^(?:\w+)/,/^(?:[\w"."]+)/,/^(?:\\\{)/,/^(?:.)/,/^(?:$)/,/^(?:([^"<"\s])+)/],
conditions: {"comment":{"rules":[11,12,13,25],"inclusive":true},"escape":{"rules":[24,25],"inclusive":true},"tag":{"rules":[0,4,5,6,9,14,16,21],"inclusive":false},"var":{"rules":[15,22],"inclusive":false},"attribval":{"rules":[7,8],"inclusive":false},"djtag":{"rules":[1,17,18,21],"inclusive":false},"INITIAL":{"rules":[1,2,3,10,14,16,19,20,23,25,26],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}